---
include:
  - board: seeeduino_xiao_ble
    shield: lalapadgen2_right rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: lalapadgen2_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: seeeduino_xiao_ble        # ← xiao_ble/nrf52840 から変更
    shield: prospector_scanner
    artifact-name: prospector_scanner
